### ISSUE TITLE
use `FRAGMENT` identifiers instead of `QUERY` identifiers

### ISSUE THREAD

**Issue by lara-rium** [sunsided/query-string-builder#11]
this is a quote from this pr comment: https://github.com/twilight-rs/twilight/pull/2348#discussion_r1611064897

**Comment by sunsided** [comment]
Thanks for bringing that up. I saw the comment yesterday, but it seems to address something different.

The fragment is the part after the `#` (and not meant to be sent to a server).

![image](https://github.com/sunsided/query-string-builder/assets/495335/c3d44f40-bd1d-49cb-a213-08388473558b)

I also updated the encoding in [0.4.2](https://github.com/sunsided/query-string-builder/releases/tag/v0.4.2) with some extensions (specifically, encoding `#`, `=` etc.) even though not strictly required by RFC 3986. 

Also from https://url.spec.whatwg.org/#query-percent-encode-set:

![image](https://github.com/sunsided/query-string-builder/assets/495335/c57b39de-244a-4f1e-bad8-f2fdbda70328)

**Comment by sunsided** [comment]
... thinking about it, it seems the comment suggests that the original version incorrectly uses fragment-specific encoding when it shouldn't. Does this affect this library (particularly after 0.4.2)?

**Comment by Erk-** [comment]
I think after the change made in https://github.com/sunsided/query-string-builder/commit/b403c6d582f54e17744f91c2776c982e95ea18f0 it is no longer an issue. Thanks for the quick turnaround.

**Comment by sunsided** [comment]
Gladly! I'll close this for the time being, but feel free to follow up if more work is needed here.
